### ISSUE TITLE
No matching found when assigning connectivity through template

### ISSUE THREAD

**Issue by cescgina** [martimunicoy/peleffy#111]
When trying to load a molecule withouth bond orders  using a connectivity_template I get the following error
```python
Traceback (most recent call last):
  File "reproduce.py", line 4, in <module>
    mol = Molecule("cluster1.min.imaged.pdb", connectivity_template=molecule.rdkit_molecule)
  File "/home/jfrancesc/offpele/peleffy/topology/molecule.py", line 544, in __init__
    self._initialize_from_pdb(path)
  File "/home/jfrancesc/offpele/peleffy/topology/molecule.py", line 596, in _initialize_from_pdb
    rdkit_toolkit.assign_connectivity_from_template(self)
  File "/home/jfrancesc/offpele/peleffy/utils/toolkits.py", line 164, in assign_connectivity_from_template
    molecule.connectivity_template, rdkit_molecule)
  File "/home/jfrancesc/miniconda3/envs/offpele_env/lib/python3.7/site-packages/rdkit/Chem/AllChem.py", line 437, in AssignBondOrdersFromTemplate
    raise ValueError("No matching found")
ValueError: No matching found
```

PDB files seem properly formatted and upon visual inspection the molecules seem equivalent. I attached in the zip file the two pdb and short script to reproduce the issue.
[data_reproduce.zip](https://github.com/martimunicoy/peleffy/files/5608860/data_reproduce.zip)

**Comment by martimunicoy** [comment]
Thanks Joan, taking a look at it...

**Comment by martimunicoy** [comment]
This issue seems a consequence of using PDB files with an empty `Element` column. Then, atoms like Cl might not be correctly interpreted by RDKit.

Only when the `Element` column is missing, we could try to infer the element using the PDB atom name.

**Comment by cescgina** [comment]
With PR #112  merged, the issue is resolved.
