### ISSUE TITLE
Error at generating template files with peleffy

### ISSUE THREAD

**Issue by etiur** [martimunicoy/peleffy#156]
I was trying to generate a template file for a cofactor, FAD,  in 'OPLS2005' using the version of peleffy in this conda envinronment in marenostrum 0

conda activate /gpfs/projects/bsc72/conda_envs/platform/1.6.0

But it gave this error

Traceback (most recent call last):
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/site-packages/peleffy/main.py", line 299, in <module>
    main(args)
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/site-packages/peleffy/main.py", line 283, in main
    run_peleffy(pdb_file=args.pdb_file,
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/site-packages/peleffy/main.py", line 215, in run_peleffy
    topology = Topology(molecule, parameters)
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/site-packages/peleffy/topology/topology.py", line 71, in __init__
    self._build()
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/site-packages/peleffy/topology/topology.py", line 88, in _build
    or len(list(self.parameters.atom_iterator)) == 0):
  File "/gpfs/projects/bsc72/conda_envs/platform/1.6.0/lib/python3.8/site-packages/peleffy/forcefield/parameters.py", line 333, in atom_iterator
    assert len(self['atom_names']) == len(self['atom_types']) \
AssertionError: Size of atom parameter lists should match

I upload the FAD in format txt, but you should be able to change it back to pdb easily by rename it.
[FAD.txt](https://github.com/martimunicoy/peleffy/files/7279261/FAD.txt)

This the job file I used
[NDP.txt](https://github.com/martimunicoy/peleffy/files/7279280/NDP.txt)

**Comment by laumalo** [comment]
As a temporary solution, I attach the templates that whould be generated with this PDB file,
[templates.zip](https://github.com/martimunicoy/peleffy/files/7286881/templates.zip)

**Comment by martimunicoy** [comment]
This issue might be solved now with bugfix from PR #159.
